#!/bin/bash 

for f in pacli_env_config; do
    [ -e "$f" ] || {
    echo "Seems like you don't have a pacli_env_config file."
    echo "Pacli shel wouldn't work correctly without that file."
    echo "We can configure it right now if you want to."
    echo "To do so you'll need to know the exact your pacli and slimcoind location."
    echo "If you don't have those data right now. You can start pacli_env later when you have them."
    read -p "Would you like to create pacli_env_config file now? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1
    read -e -p "Please enter the absolute path to your pacli location, including the word 'pacli' as well (the default location is already written, if it's correct just press Enter to confirm): " -i "$HOME/.local/bin/pacli" pacli
    if [[ ! -f $pacli ]] ; then     
        echo "There is no pacli file in that location, please check and try again." 
        exit 1
    fi
    echo 'path_to_pacli=''"'$pacli'"' > pacli_env_config

    read -p "Please enter the absolute path to your slimcoind location, including the word 'slimcoind'  : " slimcoind
    if [[ ! -f $slimcoind ]]; then
        echo "There is no slimcoind file in that location, please check and try again."
        rm pacli_env_config
        exit 1
    fi
    echo  'slm=''"'$slimcoind'"'  >> pacli_env_config
    echo "Thank you!"
    }
    break
done


rlwrap -a -N -w 40 ./pre_pacli_env
