#!/usr/bin/env bash
if [ -x /bin/pacli ]; then PACLI=/bin/pacli
elif [ -x "$HOME/.local/bin/pacli" ]; then PACLI="$HOME/.local/bin/pacli"
else
  echo "pacli not found in /bin or ~/.local/bin" >&2; exit 1
fi
# start frontend pre_pacli_env with rlwrap + word list:
exec rlwrap -a -N -w 40 -f "$HOME/.pacli_words" ./pre_pacli_env
